### ISSUE TITLE
Handling Empty and Array returns from bp_get_profile_field_data

### ISSUE THREAD

**Issue by garrett-eclipse** [VibeThemes/WPLMS-Coauthors-Plus#5]
We should handle the response of bp_get_profile_field_data in the cases it returns false or as an array.
Associated Thread on WPLMS forum;
http://vibethemes.com/documentation/wplms/forums/topic/handling-empty-and-array-returns-from-bp_get_profile_field_data/

**Comment by garretthyder** [comment]
Thanks @MrVibe
